# This is default configuration for Azure VMs:

### Uncomment this if needed to make ROOT user login remotely, and there is NO such... ###
- remote_user: ubuntu
  hosts: all
  # Adjusted for Hetzner/Azure/AWS/etc.: Ubuntu 16.04 has only python3 here:
  vars:
    ansible_python_interpreter: /usr/bin/python3
  roles:
    - allow_root_login

###
### if Digital Ocean: Comment the above section!
###
#
# Now we can proceed as always. Remote ROOT login should be already enabled.
#
- hosts: all
  # Adjusted for Hetzner/Azure/AWS/etc.: Ubuntu 16.04 has only python3 here:
  vars:
    ansible_python_interpreter: /usr/bin/python3
  roles:
    - docker_host
