---
#
##################### Download and run shared initial commands: ###########################
#
- name: Cleanup previously downloaded initial.yml
  local_action:
    module: file
    state: absent
    path: "/tmp/initial.yml"
    force: yes

- name: Download shared initial.yml
  local_action:
    module: get_url
    url: https://raw.githubusercontent.com/divlv/playbooks/master/shared/initial.yml
    dest: /tmp/initial.yml

- include: /tmp/initial.yml
  static: no
#
###########################################################################################
#
- include: googledns.yml
- include: autoexec_bat.yml
- include: docker.yml
- include: firewall.yml
- include: letsencrypt.yml
- include: reboot.yml
#
# Create Portainer instance for Docker Host:
#
- name: Create Docker volume for Portainer
  command: "docker volume create portainer_data"
  ignore_errors: true

- name: Starting Portainer Docker image
  command: docker run -d --restart always -p 19000:9000 -v /var/run/docker.sock:/var/run/docker.sock -v portainer_data:/data portainer/portainer

- name: Copy Portainer start script
  copy: src=portainer dest=/root/portainer mode=0777
#
