- debug:
    msg: "Preparing infrastructure for Headless Chrome Docker image"

- name: Create Docker directory
  file: path=/opt
        state=directory
        mode=0775

- name: Copy build script
  copy: src=dockerbuild.sh dest=/opt/dockerbuild.sh mode=0777

- name: Building Headless Chrome Docker Image
  command: /opt/dockerbuild.sh
