---
#
- include: initial.yml
- include: docker.yml
- include: reboot.yml
- include: chrome.yml
- include: firewall.yml
- include: reboot.yml
#
- name: Starting Headless Chrome Docker image
  command: "docker run --shm-size=256m -d -p {{ rendertron_port }}:8080 rendertron"
#
