#!/bin/bash
#
# Sample GHOST start script
#
cd {{ ghost_dir }} 
#
#docker build -t {{ blog_image }} . 

docker run -d -p {{ ghost_port }}:2368 -e url={{ blog_domain }} -v {{ ghost_data_dir }}:/var/lib/ghost/content {{ blog_image }}

#