#!/bin/bash
#
# GHOST data backup upload script
#
#cd {{ ghost_dir }} 
#
#
#
today=$(date +%m-%d)
#
#
# Here we're finding the latest backup (grepping only for "{{ pg_db_name }}" database backup files)
backupfile=$(find {{ blog_backup_dir }} -type f -printf '%T@ %p\n' | grep {{ blog_image }}_$today | sort -n | tail -1 | cut -f2- -d" ")

echo $backupfile

