#!/bin/bash

echo "###################################################################"
echo "Registering helper tools..."
echo "###################################################################"


# Don't forget to make the scripts executable via GIT: git add --chmod=+x <script-name>
# Cleanup part:

# Cleanup the old scripts if they exist
rm -f /usr/bin/getsize
rm -f /usr/bin/ffind
rm -f /usr/bin/ports
rm -f /usr/bin/portsa
rm -f /usr/bin/dstop
rm -f /usr/bin/iptl
rm -f /usr/bin/checkport
rm -f /usr/bin/myip


#################################################

# Create part:

# Copy the new scripts to the /usr/bin directory
cp ./getsize /usr/bin/getsize
cp ./ffind /usr/bin/ffind
cp ./ports /usr/bin/ports
cp ./portsa /usr/bin/portsa
cp ./dstop /usr/bin/dstop
cp ./iptl /usr/bin/iptl
cp ./checkport /usr/bin/checkport
cp ./myip /usr/bin/myip

# Make scripts executable
chmod +x /usr/bin/getsize
chmod +x /usr/bin/ffind
chmod +x /usr/bin/ports
chmod +x /usr/bin/portsa
chmod +x /usr/bin/dstop
chmod +x /usr/bin/iptl
chmod +x /usr/bin/checkport
chmod +x /usr/bin/myip

echo "###################################################################"
echo "Registration complete!"
echo "###################################################################"
