# This ghost installation should be applied on to existing "docker_host"
#
# Now we can proceed as always. Remote ROOT login should be already enabled.
#
- hosts: all
  # Adjusted for Hetzner/Azure/AWS/etc.: Ubuntu 16.04 has only python3 here:
  vars:
    ansible_python_interpreter: /usr/bin/python3
  roles:
  - ghost
