- name: Create GHOST directory
  file: path={{ ghost_dir }}
        state=directory
        mode=0775

- name: Create GHOST data directory
  file: path={{ ghost_data_dir }}
        state=directory
        mode=0775

- name: Copy GHOST start script
  template: src=start dest={{ ghost_dir }}/start mode=0777

- name: Copy GHOST stop script
  template: src=stop dest={{ ghost_dir }}/stop mode=0777

- name: Build and start GHOST
  command: "{{ ghost_dir }}/start"
