- name: Install add-apt-repostory
  become: yes
  apt: name=software-properties-common state=latest

- name: Add Oracle Java Repository
  become: yes
  apt_repository: repo='ppa:webupd8team/java'

- name: Update APT
  command: apt-get update

- name: Autoaccept license for Java
  become: yes
  debconf: name='oracle-java7-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

- name: Install Oracle Java 7
  become: yes
  apt: name={{item}} state=latest
  with_items:
    - oracle-java7-installer
    - ca-certificates
    - oracle-java7-set-default

