---

- name: TomCat -=- Download from tomcat.apache.org
  get_url: url="http://www-eu.apache.org/dist/tomcat/tomcat-7/v7.0.85/bin/{{ tomcat_archive }}.zip" dest="{{ tomcat_download_dir }}/{{ tomcat_archive }}.zip"

- name: TomCat -=- Extract archive
  command: chdir={{ tomcat_download_dir }} unzip -q {{ tomcat_download_dir }}/{{ tomcat_archive }}.zip

 