---

- name: TomCat -=- Download from tomcat.apache.org
  get_url: url="http://www-eu.apache.org/dist/tomcat/tomcat-7/v7.0.85/bin/{{ tomcat_archive }}.zip" dest="{{ tomcat_download_dir }}/{{ tomcat_archive }}.zip"

- name: TomCat -=- Delete old tomcat dir, if any
  file: path="{{ tomcat_real_work_dir }}" state=absent
  ignore_errors: yes
  
- name: TomCat -=- Extract archive
  command: chdir=/opt unzip -q {{ tomcat_download_dir }}/{{ tomcat_archive }}.zip

- name: TomCat -=- Add group
  group: name={{ tomcat_group }}

- name: TomCat -=- Add user
  user: name={{ tomcat_user }} group={{ tomcat_group }} home={{ tomcat_real_work_dir }} shell=/bin/false
  
- name: TomCat -=- Create symbolic link to installation dir
  file:
    src: "{{ tomcat_real_work_dir }}"
    dest: "{{ tomcat_work_dir }}"
    state: link

#- name: TomCat -=- Create tomcat init script
#  template: src=tomcat.sh dest=/etc/init.d/tomcat owner=root group=root mode=0766

- name: TomCat -=- Create tomcat systemd service script
  template: src=tomcat.service dest=/etc/systemd/system/tomcat.service owner=root group=root mode=0766
  
- name: TomCat -=- Set file permissions
  file: path={{ tomcat_real_work_dir }} owner={{ tomcat_user }} group=tomcat recurse=yes

- name: TomCat -=- Permissions for executable files
  file: dest="{{ tomcat_real_work_dir }}/bin/*.sh" mode=766
  
- name: TomCat -=- Configure server
  template: src=server.xml.7 dest="{{ catalina_home }}/conf/server.xml" backup=yes

- name: TomCat -=- Configure users
  template: src=tomcat-users.xml dest="{{ catalina_home }}/conf/"

- name: TomCat -=- Start service
  shell: /etc/init.d/tomcat start
